name: Java CI

on:
  push:
    branches:
      - 3.x
  pull_request:
    branches: 
      - 3.x

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B clean package integration-test --file releng/org.eclipse.fx.releng/pom.xml
