name: Java CI

on:
  push:
    branches:
      - 3.x
  pull_request:
    branches: 
      - 3.x

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Download old Maven
      run: wget -q https://archive.apache.org/dist/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.zip
    - name: Unzip old maven
      run: unzip apache-maven-3.5.4-bin.zip
    - name: Build with old Maven
      run: ./apache-maven-3.5.4/bin/mvn -q -B clean package integration-test --file releng/org.eclipse.fx.releng/pom.xml
