name: Java CI

on:
  push:
    branches:
      - 3.x
  pull_request:
    branches: 
      - 3.x

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
#    - name: Set up JDK 1.8
#      uses: actions/setup-java@v1
#      with:
#        java-version: 1.8
    - name: Java Info
      run: which java
    - name: Install ZuluFX
      run: wget -q https://cdn.azul.com/zulu/bin/zulu8.42.0.23-ca-fx-jdk8.0.232-linux_x64.tar.gz
    - name: Extract ZuluFX
      run: tar xzvf zulu8.42.0.23-ca-fx-jdk8.0.232-linux_x64.tar.gz
    - name: Test Java
      run: zulu8.42.0.23-ca-fx-jdk8.0.232-linux_x64/bin/java -version
    - name: Export JAVA_HOME
      run: export JAVA_HOME=${GITHUB_WORKSPACE}/zulu8.42.0.23-ca-fx-jdk8.0.232-linux_x64; echo $JAVA_HOME
    - name: Cur Dir
      run: pwd
    - name: Update Path
      run: export PATH=${GITHUB_WORKSPACE}/zulu8.42.0.23-ca-fx-jdk8.0.232-linux_x64/bin:$PATH; echo $PATH
    - name: Test Java 2
      run: java -version
    - name: Java Info
      run: which java
    - name: Download old Maven
      run: wget -q https://archive.apache.org/dist/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.zip
    - name: Unzip old maven
      run: unzip apache-maven-3.5.4-bin.zip
    - name: Build with old Maven
      run: ./apache-maven-3.5.4/bin/mvn --version
#      run: ./apache-maven-3.5.4/bin/mvn -q -B clean package integration-test --file releng/org.eclipse.fx.releng/pom.xml
